Algoritmo "exercicio_5"
//Faça um algoritmo (fluxograma e psedocodigo ViuAlg) que recebe
//o Raio (R) de uma circunferência,
//calcula e mostra o valor de sua Área (sabendo que A = p.R2)

Var
areadoCircuferencia, raio: real

Inicio
escreva("Informe o raio da circuferencia: ")
leia(raio)

areadoCircuferencia <- 3.14 * raio^2

escreva("A area da circuferencia eh de aproximadamente", areadoCircuferencia)

Fimalgoritmo